### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by thombook** [RenWal/fritzbox-munin-fast#4]
the plugins are currently failing with:

2022/08/13-07:23:23 Munin::Node::Server (type Net::Server::Fork) starting! pid(4147623)
Binding to TCP port 4949 on host 127.0.0.1 with IPv4
Setting gid to "0 0"
2022/08/13-07:23:23 [4147623] Error output from fritzbox_dsl.py:
2022/08/13-07:23:23 [4147623]   Traceback (most recent call last):
2022/08/13-07:23:23 [4147623]     File "/etc/munin/plugins/fritzbox_dsl.py", line 150, in <module>
2022/08/13-07:23:23 [4147623]       print_config()
2022/08/13-07:23:23 [4147623]     File "/etc/munin/plugins/fritzbox_dsl.py", line 114, in print_config
2022/08/13-07:23:23 [4147623]       modes = get_modes()
2022/08/13-07:23:23 [4147623]     File "/etc/munin/plugins/fritzbox_dsl.py", line 55, in get_modes
2022/08/13-07:23:23 [4147623]       return os.getenv('dsl_modes').split(' ')
2022/08/13-07:23:23 [4147623]   AttributeError: 'NoneType' object has no attribute 'split'
2022/08/13-07:23:23 [4147623] Service 'fritzbox_dsl.py' exited with status 1/0.
2022/08/13-07:23:24 [4147623] Error output from fritzbox_energy.py:
2022/08/13-07:23:24 [4147623]   Traceback (most recent call last):
2022/08/13-07:23:24 [4147623]     File "/etc/munin/plugins/fritzbox_energy.py", line 166, in <module>
2022/08/13-07:23:24 [4147623]       print_config()
2022/08/13-07:23:24 [4147623]     File "/etc/munin/plugins/fritzbox_energy.py", line 114, in print_config
2022/08/13-07:23:24 [4147623]       modes = get_modes()
2022/08/13-07:23:24 [4147623]     File "/etc/munin/plugins/fritzbox_energy.py", line 54, in get_modes
2022/08/13-07:23:24 [4147623]       return os.getenv('energy_modes').split(' ')
2022/08/13-07:23:24 [4147623]   AttributeError: 'NoneType' object has no attribute 'split'
2022/08/13-07:23:24 [4147623] Service 'fritzbox_energy.py' exited with status 1/0.
2022/08/13-07:23:24 [4147623] Error output from fritzbox_ecostat.py:
2022/08/13-07:23:24 [4147623]   Traceback (most recent call last):
2022/08/13-07:23:24 [4147623]     File "/etc/munin/plugins/fritzbox_ecostat.py", line 119, in <module>
2022/08/13-07:23:24 [4147623]       print_config()
2022/08/13-07:23:24 [4147623]     File "/etc/munin/plugins/fritzbox_ecostat.py", line 75, in print_config
2022/08/13-07:23:24 [4147623]       modes = get_modes()
2022/08/13-07:23:24 [4147623]     File "/etc/munin/plugins/fritzbox_ecostat.py", line 34, in get_modes
2022/08/13-07:23:24 [4147623]       return os.getenv('ecostat_modes').split(' ')
2022/08/13-07:23:24 [4147623]   AttributeError: 'NoneType' object has no attribute 'split'
2022/08/13-07:23:24 [4147623] Service 'fritzbox_ecostat.py' exited with status 1/0.
2022/08/13-07:23:28 [4147623] Error output from fritzbox_wifi_load.py:
2022/08/13-07:23:28 [4147623]   Traceback (most recent call last):
2022/08/13-07:23:28 [4147623]     File "/etc/munin/plugins/fritzbox_wifi_load.py", line 125, in <module>
2022/08/13-07:23:28 [4147623]       print_config()
2022/08/13-07:23:28 [4147623]     File "/etc/munin/plugins/fritzbox_wifi_load.py", line 95, in print_config
2022/08/13-07:23:28 [4147623]       freqs = get_freqs()
2022/08/13-07:23:28 [4147623]     File "/etc/munin/plugins/fritzbox_wifi_load.py", line 48, in get_freqs
2022/08/13-07:23:28 [4147623]       return os.getenv('wifi_freqs').split(' ')
2022/08/13-07:23:28 [4147623]   AttributeError: 'NoneType' object has no attribute 'split'
2022/08/13-07:23:28 [4147623] Service 'fritzbox_wifi_load.py' exited with status 1/0.

**Comment by RenWal** [comment]
Huh, so `os.getenv('dsl_modes')` is returning `None`. That looks like missing configuration to me.

Did you follow the guidance given in https://github.com/RenWal/fritzbox-munin-fast/blob/master/src/fritzbox_dsl.py#L10 (a similar header should exist in the other files) with regard to the configuration options that should be set, and did you restart `munin-node` afterwards?

For example, to get all graphs, you should have `env.dsl_modes capacity snr damping errors crc` in your config for `fritzbox_dsl`.

**Comment by thombook** [comment]
baa. totally my fault, please apologize :-( for whatever reasons I thought that I could reuse my old config for https://github.com/Tafkas/fritzbox-munin without any change... Closing therefore. Thanks for your quick response on this - works like a charm now!
